### ISSUE TITLE
Cannot join a room / Room cannot be joined

### ISSUE THREAD

**Issue by sushixx** [Zedruc/ATC24-Suite-Feedback#1]
**Describe the bug**
Friends are not able to join my room/ I am not able to join their room

**To Reproduce**
1. Friend creates room and sends the room code
2. I click "Join Room" and paste the  sent room code
3. Click "Join"
4. Pop up appears on bottom right "Room with this code doesn't exist"

**Expected behavior**
Expected to have two members within the same room for cooperation.

**Screenshots**
![image](https://github.com/Zedruc/ATC24-Suite-Feedback/assets/161615143/e8ea70f8-6d12-4f2a-a83f-415561fcb4da)
![image](https://github.com/Zedruc/ATC24-Suite-Feedback/assets/161615143/e084b9b1-a11e-45cc-aaa2-2adc981b2d18)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - OS: Windows 10
 - Browser: OperaGX

**Additional context**
The problem works both ways, friend cannot join my room.
Friends OS: Monterey ver. 12.5.1
Browser: Safari

**Comment by sushixx** [comment]
Friend and I tried to use Chrome instead but to no avail. Still showed "Room with this code does not exist.

**Comment by Zedruc** [comment]
> Friend and I tried to use Chrome instead but to no avail. Still showed "Room with this code does not exist.

Hey thanks for reporting.

**Comment by Zedruc** [comment]
# Issue resolved
The bug was specific to the client and is suspected to be caused by some invalid, leftover data from Version 1 of the ATC24-Suite.

# How to fix
Press the lock next to the URL, click "Website Settings" and click the first option "Delete Website Data",  
then reload the page using `ctrl+f5`
![Februar 29 24](https://github.com/Zedruc/ATC24-Suite-Feedback/assets/69540929/d4a508b2-ada7-482e-b344-9bf2ce5c2ea6)
